### ISSUE TITLE
合成时json出错

### ISSUE THREAD

**Issue by NSQX13579** [zhzhongshi/nonebot-plugin-diffsinger#1]
![RM0WV}6OG58U}H%U_0X`HNV](https://user-images.githubusercontent.com/102937666/198816920-24d0c612-2c6f-42b9-b86e-2499fa6ef3b6.png)
报错如图

**Comment by zhzhongshi** [comment]
服务器返回非json数据，可能是接口坏了

**Comment by zhzhongshi** [comment]
服务器返回非json数据，可能是接口坏了
